services:
  nats:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/nats:2.11.3
    container_name: nats-server
    ports:
      - "4222:4222"
      - "8222:8222"
    restart: unless-stopped
